<?php
/**
 * ACF Fields for Immigration Referral Form
 * 
 * Defines the custom fields for the immigration referral form block
 */

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key' => 'group_immigration_referral_form',
        'title' => 'Immigration Referral Form Settings',
        'fields' => array(
            array(
                'key' => 'field_immigration_form_title',
                'label' => 'Form Title',
                'name' => 'form_title',
                'type' => 'text',
                'instructions' => 'Main title for the immigration referral form',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Immigration Referral Form',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_form_subtitle',
                'label' => 'Form Subtitle',
                'name' => 'form_subtitle',
                'type' => 'text',
                'instructions' => 'Subtitle text for the form',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Begin Your Journey to a New Country',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_form_description',
                'label' => 'Form Description',
                'name' => 'form_description',
                'type' => 'textarea',
                'instructions' => 'Description text below the form title',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Our experienced immigration consultants are here to help you navigate the complex immigration process. Fill out this form to get personalized guidance for your immigration journey.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_immigration_admin_email',
                'label' => 'Admin Email',
                'name' => 'admin_email',
                'type' => 'email',
                'instructions' => 'Email address to receive form submissions',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'immigration@linkyouacademy.com',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_immigration_thank_you_page',
                'label' => 'Thank You Page URL',
                'name' => 'thank_you_page',
                'type' => 'url',
                'instructions' => 'URL to redirect after successful form submission',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '/thank-you-immigration/',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_immigration_show_whatsapp',
                'label' => 'Show WhatsApp Field',
                'name' => 'show_whatsapp',
                'type' => 'true_false',
                'instructions' => 'Display WhatsApp number field in the form',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_immigration_show_captcha',
                'label' => 'Show CAPTCHA',
                'name' => 'show_captcha',
                'type' => 'true_false',
                'instructions' => 'Display CAPTCHA verification in the form',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_immigration_enable_file_upload',
                'label' => 'Enable File Upload',
                'name' => 'enable_file_upload',
                'type' => 'true_false',
                'instructions' => 'Allow users to upload documents',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_immigration_max_file_size',
                'label' => 'Max File Size (MB)',
                'name' => 'max_file_size',
                'type' => 'number',
                'instructions' => 'Maximum file size allowed for uploads in megabytes',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_immigration_enable_file_upload',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 5,
                'placeholder' => '',
                'prepend' => '',
                'append' => 'MB',
                'min' => 1,
                'max' => 50,
                'step' => 1,
            ),
            array(
                'key' => 'field_immigration_allowed_file_types',
                'label' => 'Allowed File Types',
                'name' => 'allowed_file_types',
                'type' => 'checkbox',
                'instructions' => 'Select which file types are allowed for upload',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_immigration_enable_file_upload',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '75',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'pdf' => 'PDF (.pdf)',
                    'doc' => 'Word Document (.doc)',
                    'docx' => 'Word Document (.docx)',
                    'jpg' => 'JPEG Image (.jpg)',
                    'jpeg' => 'JPEG Image (.jpeg)',
                    'png' => 'PNG Image (.png)',
                ),
                'allow_custom' => 0,
                'default_value' => array(
                    0 => 'pdf',
                    1 => 'doc',
                    2 => 'docx',
                    3 => 'jpg',
                    4 => 'jpeg',
                    5 => 'png',
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
                'save_custom' => 0,
            ),
            array(
                'key' => 'field_immigration_button_text',
                'label' => 'Submit Button Text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => 'Text for the form submit button',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Submit Immigration Referral',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_form_background',
                'label' => 'Form Background Style',
                'name' => 'form_background',
                'type' => 'select',
                'instructions' => 'Choose the background style for the form',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'gradient' => 'Gradient Background',
                    'solid' => 'Solid Background',
                    'transparent' => 'Transparent',
                ),
                'default_value' => array(
                    0 => 'gradient',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/immigration-referral-form',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Thank You Page ACF Fields
    acf_add_local_field_group(array(
        'key' => 'group_immigration_thank_you',
        'title' => 'Immigration Thank You Page Settings',
        'fields' => array(
            array(
                'key' => 'field_immigration_thank_you_title',
                'label' => 'Thank You Title',
                'name' => 'thank_you_title',
                'type' => 'text',
                'instructions' => 'Main title for the thank you page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Thank You for Your Immigration Referral!',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_thank_you_subtitle',
                'label' => 'Thank You Subtitle',
                'name' => 'thank_you_subtitle',
                'type' => 'text',
                'instructions' => 'Subtitle for the thank you page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Your application has been successfully submitted',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_thank_you_message',
                'label' => 'Thank You Message',
                'name' => 'thank_you_message',
                'type' => 'textarea',
                'instructions' => 'Main message content for the thank you page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Our immigration consultants will review your application and contact you within 24 hours to discuss your immigration options and next steps.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_immigration_next_steps_title',
                'label' => 'Next Steps Title',
                'name' => 'next_steps_title',
                'type' => 'text',
                'instructions' => 'Title for the next steps section',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'What Happens Next?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_contact_info_title',
                'label' => 'Contact Info Title',
                'name' => 'contact_info_title',
                'type' => 'text',
                'instructions' => 'Title for the contact information section',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Need Immediate Assistance?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_immigration_next_steps',
                'label' => 'Next Steps',
                'name' => 'next_steps',
                'type' => 'repeater',
                'instructions' => 'Add the steps in the immigration process',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_immigration_step_title',
                'min' => 1,
                'max' => 6,
                'layout' => 'table',
                'button_label' => 'Add Step',
                'sub_fields' => array(
                    array(
                        'key' => 'field_immigration_step_number',
                        'label' => 'Step Number',
                        'name' => 'step_number',
                        'type' => 'text',
                        'instructions' => 'Step number (1, 2, 3, etc.)',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '1',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 2,
                    ),
                    array(
                        'key' => 'field_immigration_step_title',
                        'label' => 'Step Title',
                        'name' => 'step_title',
                        'type' => 'text',
                        'instructions' => 'Title for this step',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Application Review',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_immigration_step_description',
                        'label' => 'Step Description',
                        'name' => 'step_description',
                        'type' => 'textarea',
                        'instructions' => 'Description of what happens in this step',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '45',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Our immigration experts will carefully review your application...',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_immigration_step_icon',
                        'label' => 'Step Icon',
                        'name' => 'step_icon',
                        'type' => 'select',
                        'instructions' => 'Choose an icon for this step',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'document-search' => 'Document Search',
                            'phone' => 'Phone',
                            'chart-bar' => 'Chart Bar',
                            'clipboard-check' => 'Clipboard Check',
                            'user' => 'User',
                            'mail' => 'Mail',
                            'globe' => 'Globe',
                            'check' => 'Check',
                        ),
                        'default_value' => array(
                            0 => 'document-search',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/thank-you-immigration',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

}

// Populate default next steps data
add_filter('acf/load_field/name=next_steps', 'populate_immigration_next_steps_defaults');
function populate_immigration_next_steps_defaults($field)
{
    if (empty($field['value'])) {
        $field['value'] = array(
            array(
                'step_number' => '1',
                'step_title' => 'Application Review',
                'step_description' => 'Our immigration experts will carefully review your application and documents within 24 hours.',
                'step_icon' => 'document-search'
            ),
            array(
                'step_number' => '2',
                'step_title' => 'Consultation Call',
                'step_description' => 'We will contact you via your preferred method to discuss your immigration options and create a personalized plan.',
                'step_icon' => 'phone'
            ),
            array(
                'step_number' => '3',
                'step_title' => 'Immigration Strategy',
                'step_description' => 'Together, we will develop a comprehensive immigration strategy tailored to your specific situation and goals.',
                'step_icon' => 'chart-bar'
            ),
            array(
                'step_number' => '4',
                'step_title' => 'Application Process',
                'step_description' => 'We will guide you through every step of the immigration application process to maximize your chances of success.',
                'step_icon' => 'clipboard-check'
            )
        );
    }
    return $field;
}
?>