<?php
/**
 * ACF Fields for About Us Page
 * 
 * This file contains the ACF field definitions for the About Us page block.
 * Make sure to include this file in functions.php or call it when needed.
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_about_us_page',
    'title' => 'About Us Page Fields',
    'fields' => array(

        array(
            'key' => 'field_about_company_description',
            'label' => 'Company Description',
            'name' => 'company_description',
            'type' => 'textarea',
            'instructions' => 'Main description about the company',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'LinkYou.Marketing Is One of The Best Digital Marketing Agencies Mainly Located in Canada, Milton. Let us take care of your online presence!',
            'placeholder' => 'Company description...',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_about_company_stats',
            'label' => 'Company Statistics',
            'name' => 'company_stats',
            'type' => 'repeater',
            'instructions' => 'Add company statistics and achievements',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 6,
            'layout' => 'table',
            'button_label' => 'Add Statistic',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_stat_number',
                    'label' => 'Number',
                    'name' => 'number',
                    'type' => 'text',
                    'instructions' => 'The statistic number (e.g., 50+, 100K+, 5/5)',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '50+',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_about_stat_label',
                    'label' => 'Label',
                    'name' => 'label',
                    'type' => 'text',
                    'instructions' => 'Description of the statistic',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Projects Completed',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_about_team_members',
            'label' => 'Team Members',
            'name' => 'team_members',
            'type' => 'repeater',
            'instructions' => 'Add team member information',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 10,
            'layout' => 'block',
            'button_label' => 'Add Team Member',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_member_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => 'Team member name',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'John Doe',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_about_member_position',
                    'label' => 'Position',
                    'name' => 'position',
                    'type' => 'text',
                    'instructions' => 'Team member position/role',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Marketing Director',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_about_member_image',
                    'label' => 'Photo',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => 'Team member photo',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_about_member_bio',
                    'label' => 'Bio',
                    'name' => 'bio',
                    'type' => 'textarea',
                    'instructions' => 'Brief bio of the team member',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Brief description of the team member...',
                    'maxlength' => '',
                    'rows' => 3,
                    'new_lines' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_about_services',
            'label' => 'Services',
            'name' => 'services',
            'type' => 'repeater',
            'instructions' => 'Add services provided by the company',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 8,
            'layout' => 'block',
            'button_label' => 'Add Service',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_service_icon',
                    'label' => 'Icon',
                    'name' => 'icon',
                    'type' => 'text',
                    'instructions' => 'Emoji or icon for the service',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '📈',
                    'placeholder' => '📈',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_about_service_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Service title',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '75',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Digital Marketing',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_about_service_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Service description',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Service description...',
                    'maxlength' => '',
                    'rows' => 3,
                    'new_lines' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_about_cta_title',
            'label' => 'CTA Section Title',
            'name' => 'cta_title',
            'type' => 'text',
            'instructions' => 'Call to action section title',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Ready to Transform Your Business?',
            'placeholder' => 'Ready to Transform Your Business?',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_about_cta_subtitle',
            'label' => 'CTA Section Subtitle',
            'name' => 'cta_subtitle',
            'type' => 'textarea',
            'instructions' => 'Call to action section subtitle',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Join hundreds of satisfied clients who are already getting more sales and increasing profits with LinkYou.Marketing',
            'placeholder' => 'CTA subtitle text...',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_about_cta_button_text',
            'label' => 'CTA Button Text',
            'name' => 'cta_button_text',
            'type' => 'text',
            'instructions' => 'Text for the call to action button',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Start Your Journey Today',
            'placeholder' => 'Get Started',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_about_cta_button_link',
            'label' => 'CTA Button Link',
            'name' => 'cta_button_link',
            'type' => 'url',
            'instructions' => 'Link for the call to action button',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '#contact',
            'placeholder' => 'https://example.com/contact',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/about-us-block',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Fields for the About Us page block',
));

endif;
